Cleaned and remade feature extraction.
LASR-at-Home/Base pull request #159
Opened 2024-04-18 13:56 UTC by MBTMBTMBT

2024-04-18 16:46 UTC, jws-1 requested changes
Awaiting changes

2024-04-18 16:46 UTC, jws-1 commented on tasks/receptionist/launch/setup.launch
> +    <node pkg="lasr_vision_yolov8" type="service" name="yolo_service" output="screen"/>
```suggestion
```

2024-04-18 16:46 UTC, jws-1 commented on tasks/receptionist/src/receptionist/head_direction_test.py
> +
Remove

2024-04-18 16:46 UTC, jws-1 commented on tasks/receptionist/src/receptionist/states/speakdescriptions.py
> +
Remove

2024-04-19 10:53 UTC, MBTMBTMBT commented on common/vision/lasr_vision_bodypix/src/lasr_vision_bodypix/bodypix.py
> +            # model = load_model(download_model(BodyPixModelPaths.RESNET50_FLOAT_STRIDE_16))
Options of loading different models are kept, no longer loading any model from local folder (unless downloaded automatically).

2024-04-23 13:20 UTC, jws-1 approved these changes
Couple of minor comments, but the rest looks good! Looking forward to seeing a live demonstration, and then we can merge this in! :partying_face:

2024-04-23 15:55 UTC, MBTMBTMBT commented on common/vision/lasr_vision_feature_extraction/package.xml
> +  <description>Custormer attribute extraction, encluding face and cloth, implemented with PyTorch customed models.</description>
Haha sorry! Bad languagev:)

2024-04-23 16:25 UTC, MBTMBTMBT commented on skills/src/lasr_skills/vision/get_image.py
> +            return 'failed'
I renamed it and canceled the loop. I think I'll solve this synchronization in the future :)

2024-04-23 21:14 UTC, jws-1 approved these changes
Good job. (Also saw working demo).

2024-04-23 21:15 UTC, merged