Receptionist look at person
LASR-at-Home/Base pull request #166
Opened 2024-04-23 17:01 UTC by fireblonde

This pr includes:

- [ ] package for models
- [ ] pcl_to_img_msg
- [ ] poses in BodyPix
- [ ] look at person skill  without bbox (only works per 1 person

2024-04-23 22:11 UTC, jws-1 requested changes
Very cool piece of work, which I had the pleasure of observing being demoed on the real robot! Good job :+1:. Following this I'll open an issue for raising the torso, as we discussed.

Some very minor comments for you to consider relating to the `models` package, some small typos and general organisation.

:+1:

2024-04-23 22:11 UTC, jws-1 commented on common/helpers/models/package.xml
> +  <license>TODO</license>
```suggestion
  <license>MIT</license>
```
In-case we keep the package

2024-04-23 22:11 UTC, jws-1 commented on common/helpers/models/package.xml
> +  <maintainer email="nicole@todo.todo">nicole</maintainer>
Correct email, in case we keep the package

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +                Get3DImage("/xtion/depth_registered/points"),
```suggestion
                GetPointCloud("/xtion/depth_registered/points"),
```

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +from vision import Get3DImage
```suggestion
from vision import GetPointCloud
```

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +        # the img msg is pcl
```suggestion
```

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_to_point.py
> +                target=ud.pointstampted,
```suggestion
                target=ud.pointstamped,
```

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_to_point.py
> +            input_keys=["pointstampted"],
```suggestion
            input_keys=["pointstamped"],
```

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +                remapping={"point": "point"},
```suggestion
                remapping={"pointstamped": "pointstamped"},
```

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +                remapping={"img_msg": "img_msg", "poses": "poses", "pointstampted": "pointstampted"}
```suggestion
                remapping={"img_msg": "img_msg", "poses": "poses", "pointstamped": "pointstamped"}
```

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +                                                                     masks),
Very nice!

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +                remapping={"img_msg": "img_msg"},
```suggestion
                remapping={"pcl_msg": "pcl_msg"},
```

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +                    request_cb=lambda ud, _: BodyPixDetectionRequest(pcl_to_img_msg(ud.img_msg), "resnet50", 0.7,
```suggestion
                    request_cb=lambda ud, _: BodyPixDetectionRequest(pcl_to_img_msg(ud.pcl_msg), "resnet50", 0.7,
```

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +        return "succeeded"
Let's delete this for now, since (I think) we agreed to work on this in a separate piece of work :)

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +                                           output_keys=["masks", "poses", "pointstampted"])
```suggestion
                                           output_keys=["masks", "poses", "pointstamped"])
```

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +            self.img_pub.publish(img_msg1)
I like this, but I think we should pass the `DEBUG` flag to the constructor of the state machine instead of declaring it globally above!

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +                             output_keys=["pointstampted"])
```suggestion
                             output_keys=["pointstamped"])
```

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +class CheckEyes(smach.State):
A bit picky, but I think we should nest this inside of the `LookAtPerson` class (as it can't really be used on its own!)

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +#!/usr/bin/env python3
```suggestion
```

2024-04-23 22:11 UTC, jws-1 commented on skills/src/lasr_skills/look_at_person.py
> +        userdata.pointstampted = look_at
```suggestion
        userdata.pointstamped = look_at
```

2024-04-23 22:11 UTC, jws-1 commented on .gitignore
> +common/helpers/models/src/models
(check re `models` package)

2024-05-10 10:32 UTC, fireblonde commented on common/helpers/models/CMakeLists.txt
Initially that was the package for keeping all of the trained models as I started implementing the gesture detection and wanted to keep the pickles there. Deleting it as of now, will add it later if need be.

2024-05-24 11:30 UTC, jws-1 approved these changes
lgtm

2024-05-24 11:30 UTC, merged